### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by mhils** [mitmproxy/pdoc#200]
- [x] Fix webbrowser URL
- [x] Template Inheritance example
- [x] Fix reexported members.
- [x] Update CLI help
- [x] Setup GitHub Actions (Test-)PyPI Upload
- [x] Update own docs
- [x] Update CHANGELOG
- [x] Cleanup
